ERROR = 'error'
WRONG_USERNAME_PASSWORD = 'Username or password wrong!'
MUST_CHANGE_PASSWORD = 'You must change your password'
DISABLED_USER = 'Disabled User'
PASSWORD_USED = 'Password used'
NOT_AUTHORIZED = 'Not authorized'
